In [3]:
import numpy as np 
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # Features ( Hrs Slept, Hrs Studied)
y = np.array(([92], [86], [89]), dtype=float) # Labels(Marks obtained)
c=np.amax(X,axis=0) # Normalize
print(c)
X = X/c # Normalize
y = y/100
print(X)
print(y)

def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x * (1 - x)

 # Variable initialization
epoch=1000 #Setting training iterations
eta =0.1 #Setting learning rate (eta)
input_neurons = 2 #number of features in data set
hidden_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer
# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) # 2x3
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons)) # 1x3
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 3x1
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)

for i in range(epoch):
    #Forward Propogation
    h_ip=np.dot(X,wh) + bh # Dot product + bias
    print(h_ip)
    h_act = sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)

 #Backpropagation
 # Error at Output layer
    Eo = y-output # Error at o/p
    outgrad = sigmoid_grad(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    print("the d_output is",d_output)

# Error at Hidden later
    Eh = d_output.dot(wout.T) # .T means transpose
    hiddengrad = sigmoid_grad(h_act) # How much hidden layer wts contributed to error
    d_hidden = Eh * hiddengrad
    wout += h_act.T.dot(d_output) *eta # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *eta

print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

[3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
[[0.7189847  0.758224   0.82609653]
 [0.77621747 0.1250376  0.53253397]]
[[0.70124168 0.11067918 0.22854717]]
[[0.71194128]
 [0.02167908]
 [0.21422111]]
[[0.1126814]]
[[1.95678228 0.74119945 1.31181216]
 [1.37213517 0.43288585 0.79976489]
 [1.93770469 0.95226159 1.40966635]]
the d_output is [[0.0417662 ]
 [0.03393084]
 [0.03548963]]
[[1.95792215 0.7412623  1.31230906]
 [1.37274535 0.43291949 0.80003088]
 [1.93881074 0.95232266 1.41014843]]
the d_output is [[0.04057777]
 [0.03289729]
 [0.03433239]]
[[1.95904133 0.74134419 1.31280987]
 [1.37334447 0.43296332 0.80029898]
 [1.93989657 0.95240221 1.41063425]]
the d_output is [[0.03944246]
 [0.03190869]
 [0.03322871]]
[[1.96014011 0.74144333 1.31331357]
 [1.37393268 0.43301638 0.80056863]
 [1.94096247 0.95249851 1.41112281]]
the d_output is [[0.03835739]
 [0.03096262]
 [0.0321756 ]]
[[1.96121881 0.7415581  1.31381924]
 [1.37451015 0.4

the d_output is [[0.00485401]
 [0.00083196]
 [0.00127295]]
[[2.03217827 0.77237109 1.36202318]
 [1.41252863 0.44958904 0.82666931]
 [2.01036668 0.98225852 1.45799921]]
the d_output is [[0.00483337]
 [0.00081275]
 [0.00125613]]
[[2.03229617 0.77245034 1.36212135]
 [1.41259191 0.44963158 0.826722  ]
 [2.01047863 0.98233368 1.45809232]]
the d_output is [[0.00481295]
 [0.00079374]
 [0.0012395 ]]
[[2.03241321 0.77252911 1.36221887]
 [1.41265472 0.44967386 0.82677435]
 [2.01058974 0.98240838 1.4581848 ]]
the d_output is [[0.00479273]
 [0.00077493]
 [0.00122305]]
[[2.03252939 0.77260741 1.36231574]
 [1.41271708 0.44971589 0.82682635]
 [2.01070002 0.98248261 1.45827665]]
the d_output is [[0.00477272]
 [0.0007563 ]
 [0.00120677]]
[[2.03264472 0.77268523 1.36241197]
 [1.41277898 0.44975766 0.826878  ]
 [2.01080948 0.98255639 1.45836788]]
the d_output is [[0.00475291]
 [0.00073787]
 [0.00119066]]
[[2.03275921 0.77276259 1.36250756]
 [1.41284043 0.44979919 0.82692932]
 [2.01091814 0.98262972 1.458

[[2.04609673 0.78281236 1.37432144]
 [1.4200126  0.45520465 0.83328308]
 [2.0233734  0.99199574 1.46947701]]
the d_output is [[ 0.00281616]
 [-0.00106063]
 [-0.0003426 ]]
[[2.04612644 0.78283896 1.37435051]
 [1.42002864 0.455219   0.83329877]
 [2.02340017 0.9920198  1.46950329]]
the d_output is [[ 0.00281271]
 [-0.00106382]
 [-0.00034525]]
[[2.04615599 0.78286545 1.37437945]
 [1.42004459 0.4552333  0.83331439]
 [2.02342679 0.99204376 1.46952944]]
the d_output is [[ 0.00280927]
 [-0.001067  ]
 [-0.00034788]]
[[2.04618539 0.78289184 1.37440827]
 [1.42006047 0.45524755 0.83332995]
 [2.02345326 0.99206762 1.46955547]]
the d_output is [[ 0.00280586]
 [-0.00107015]
 [-0.00035049]]
[[2.04621463 0.78291813 1.37443696]
 [1.42007626 0.45526174 0.83334543]
 [2.02347958 0.99209138 1.46958137]]
the d_output is [[ 0.00280247]
 [-0.00107329]
 [-0.00035309]]
[[2.04624372 0.78294432 1.37446553]
 [1.42009197 0.45527587 0.83336085]
 [2.02350575 0.99211505 1.46960716]]
the d_output is [[ 0.0027991 ]
 [-0.

 [-0.00066644]]
[[2.05021621 0.78716611 1.37878956]
 [1.42224838 0.45756199 0.83570403]
 [2.02691188 0.99581945 1.47337583]]
the d_output is [[ 0.00238773]
 [-0.00145554]
 [-0.0006671 ]]
[[2.05022639 0.78717991 1.37880259]
 [1.42225396 0.45756949 0.83571113]
 [2.02691981 0.99583111 1.47338662]]
the d_output is [[ 0.00238685]
 [-0.00145635]
 [-0.00066775]]
[[2.05023653 0.78719368 1.37881559]
 [1.42225952 0.45757698 0.83571821]
 [2.02692771 0.99584275 1.47339737]]
the d_output is [[ 0.00238598]
 [-0.00145715]
 [-0.00066841]]
[[2.05024663 0.78720742 1.37882856]
 [1.42226505 0.45758445 0.83572528]
 [2.02693557 0.99585436 1.47340809]]
the d_output is [[ 0.00238511]
 [-0.00145794]
 [-0.00066905]]
[[2.05025668 0.78722114 1.37884149]
 [1.42227057 0.45759191 0.83573232]
 [2.0269434  0.99586594 1.47341878]]
the d_output is [[ 0.00238425]
 [-0.00145873]
 [-0.0006697 ]]
[[2.0502667  0.78723483 1.3788544 ]
 [1.42227606 0.45759935 0.83573935]
 [2.02695118 0.9958775  1.47342944]]
the d_output is [[ 0

 [-0.00074996]]
[[2.05178068 0.78974959 1.38109643]
 [1.42311399 0.45897019 0.83696602]
 [2.02800803 0.99794772 1.47520786]]
the d_output is [[ 0.00227534]
 [-0.00155817]
 [-0.00075015]]
[[2.05178571 0.78975993 1.38110518]
 [1.42311681 0.45897584 0.83697082]
 [2.028011   0.99795604 1.47521451]]
the d_output is [[ 0.00227508]
 [-0.00155841]
 [-0.00075035]]
[[2.05179072 0.78977026 1.38111392]
 [1.42311962 0.45898148 0.83697562]
 [2.02801396 0.99796435 1.47522115]]
the d_output is [[ 0.00227481]
 [-0.00155865]
 [-0.00075054]]
[[2.05179572 0.78978058 1.38112265]
 [1.42312242 0.45898712 0.83698042]
 [2.02801691 0.99797265 1.47522778]]
the d_output is [[ 0.00227455]
 [-0.00155888]
 [-0.00075073]]
[[2.05180071 0.78979089 1.38113137]
 [1.42312522 0.45899276 0.83698521]
 [2.02801985 0.99798094 1.4752344 ]]
the d_output is [[ 0.00227429]
 [-0.00155912]
 [-0.00075092]]
[[2.05180569 0.7898012  1.38114007]
 [1.42312801 0.45899839 0.83698999]
 [2.02802278 0.99798923 1.47524101]]
the d_output is [[ 0